index:
  path: /
  controller: App\Controller\FrontController::index

#accueil:
#  path: /accueil
#  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
#  defaults:
#  route: home

